import { ManualSection, SectionType } from "./types";

export const MANUAL_DATA: ManualSection[] = [
  {
    id: SectionType.STARTUP,
    title: {
      ja: "1. はじめる[準備]{じゅんび}",
      en: "1. Preparation (Startup)",
      vi: "1. Chuẩn bị (Bắt đầu)",
      pt: "1. Preparação (Início)",
      tl: "1. Paghahanda (Simula)",
      id: "1. Persiapan (Mulai)",
      ne: "1. तयारी (सुरुवात)",
    },
    icon: "🚀",
    pages: [
      {
        id: "login",
        pdfPage: 6,
        title: {
          ja: "ログイン（はじめる）",
          en: "Login (Start)",
          vi: "Đăng nhập (Bắt đầu)",
          pt: "Login (Iniciar)",
          tl: "Login (Simula)",
          id: "Login (Mulai)",
          ne: "लगइन (सुरु गर्नुहोस्)",
        },
        content: {
          ja: "タブレットを[使]{つか}いはじめるときの [手順]{てじゅん}です。",
          en: "Steps to start using the tablet.",
          vi: "Các bước để bắt đầu sử dụng máy tính bảng.",
          pt: "Passos para começar a usar o tablet.",
          tl: "Mga hakbang para simulan ang paggamit ng tablet.",
          id: "Langkah-langkah untuk mulai menggunakan tablet.",
          ne: "ट्याब्レット प्रयोग गर्न सुरु गर्ने चरणहरू।",
        },
        steps: [
          {
            number: 1,
            title: {
              ja: "アプリを [開]{ひら}く",
              en: "Open the App",
              vi: "Mở ứng dụng",
              pt: "Abrir o aplicativo",
              tl: "Buksan ang App",
              id: "Buka Aplikasi",
              ne: "एप खोल्नुहोस्",
            },
            description: {
              ja: "タブレット[画面]{がめん}の「OKProCon」アイコンを タップしてください。",
              en: 'Tap the "OKProCon" icon on the tablet screen.',
              vi: 'Chạm vào biểu tượng "OKProCon" trên màn hình máy tính bảng.',
              pt: 'Toque no ícone "OKProCon" na tela do tablet.',
              tl: 'I-tap ang icon na "OKProCon" sa screen ng tablet.',
              id: 'Ketuk ikon "OKProCon" di layar tablet.',
              ne: 'ट्याब्लेट स्क्रिनमा "OKProCon" आइकन ट्याप गर्नुहोस्।',
            },
            image: "/photo/1/スクリーンショット1-1 2026-03-18 144125.png",
          },
          {
            number: 2,
            title: {
              ja: "[番号]{ばんごう}を いれる",
              en: "Enter Numbers",
              vi: "Nhập số",
              pt: "Inserir números",
              tl: "Ilagay ang mga Numero",
              id: "Masukkan Nomor",
              ne: "नम्बरहरू प्रविष्ट गर्नुहोस्",
            },
            description: {
              ja: "[入力欄]{にゅうりょくらん}をタップして、「[担当者]{たんとうしゃ}コード」と「パスワード」を [数字]{すうじ}でいれてください。",
              en: 'Tap the input field and enter your "Operator Code" and "Password" in numbers.',
              vi: 'Chạm vào ô nhập liệu and nhập "Mã nhân viên" and "Mật khẩu" bằng số.',
              pt: 'Toque no campo de entrada e insira seu "Código de Operador" e "Senha" em números.',
              tl: 'I-tap ang input field at ilagay ang iyong "Operator Code" at "Password" sa mga numero.',
              id: 'Ketuk kolom input dan masukkan "Kode Operator" dan "Kata Sandi" dalam angka.',
              ne: 'इनपुट फिल्ड ट्याप गर्नुहोस् र आफ्नो "अपरेटर कोड" र "パスワード" नम्बरहरूमा प्रविष्ट गर्नुहोस्।',
            },
            image: "/photo/1/スクリーンショット1-2 2026-03-18 144946.png",
          },
          {
            number: 3,
            title: {
              ja: "「Login」を おす",
              en: 'Press "Login"',
              vi: 'Nhấn "Đăng nhập"',
              pt: 'Pressione "Login"',
              tl: 'Pindutin ang "Login"',
              id: 'Tekan "Login"',
              ne: '"Login" थिच्नुहोस्',
            },
            description: {
              ja: "[青色]{あおいろ}の「Login」ボタンを タップして、メイン[画面]{がめん}へ すすみます。",
              en: 'Tap the blue "Login" button to proceed to the main screen.',
              vi: 'Chạm vào nút "Đăng nhập" màu xanh để chuyển đến màn hình chính.',
              pt: 'Toque no botão azul "Login" para prosseguir para a tela principal.',
              tl: 'I-tap ang asul na button na "Login" para magpatuloy sa main screen.',
              id: 'Ketuk tombol "Login" berwarna biru untuk melanjutkan ke layar utama.',
              ne: 'मुख्य स्क्रिनमा जानको लागि नीलो "Login" बटन ट्याप गर्नुहोस्।',
            },
            image: "/photo/1/スクリーンショット1-3 2026-03-18 145141.png",
          },
        ],
        notes: [
          {
            ja: "[番号]{ばんごう}を 3[回]{かい} まちがえると ロックされます。[リーダー]{りーだー}に [言]{い}ってください。",
            en: "If you enter the wrong number 3 times, it will be locked. Please tell your leader.",
            vi: "Nếu bạn nhập sai số 3 lần, nó sẽ bị khóa. Vui lòng báo cho tổ trưởng.",
            pt: "Se você inserir o número errado 3 vezes, ele será bloqueado. Por favor, avise seu líder.",
            tl: "Kung maling numero ang nailagay mo ng 3 beses, mai-lock ito. Pakisabi sa iyong leader.",
            id: "Jika Anda memasukkan nomor yang salah sebanyak 3 kali, itu akan terkunci. Silakan beri tahu pemimpin Anda.",
            ne: "यदि तपाईंले ३ पटक गलत नम्बर प्रविष्ट गर्नुभयो भने, यो लक हुनेछ। कृपया आफ्नो नेतालाई भन्नुहोस्।",
          },
        ],
      },
    ],
  },
  {
    id: SectionType.INJ_PREP,
    title: {
      ja: "2.1 INJ[事前準備]{じぜんじゅんび}",
      en: "2.1 INJ Pre-preparation",
      vi: "2.1 Chuẩn bị INJ",
      pt: "2.1 Pré-preparação INJ",
      tl: "2.1 INJ Pre-preparation",
      id: "2.1 Persiapan INJ",
      ne: "2.1 INJ पूर्व-तयारी",
    },
    icon: "⚙️",
    pages: [
      {
        id: "inj-prep",
        pdfPage: 14,
        title: {
          ja: "INJ[事前準備]{じぜんじゅんび}",
          en: "INJ Pre-preparation",
          vi: "Chuẩn bị INJ",
          pt: "Pré-preparação INJ",
          tl: "INJ Pre-preparation",
          id: "Persiapan INJ",
          ne: "INJ पूर्व-तयारी",
        },
        content: {
          ja: "[成形作業]{せいけいさぎょう}を はじめる[前]{まえ}の [準備状況]{じゅんびじょうきょう}を [登録]{とうろく}します。",
          en: "Register the preparation status before starting molding work.",
          vi: "Đăng ký tình trạng chuẩn bị trước khi bắt đầu công việc đúc.",
          pt: "Registre o status de preparação antes de iniciar o trabalho de moldagem.",
          tl: "I-register ang katayuan ng paghahanda bago simulan ang paggawa ng molding.",
          id: "Daftarkan status persiapan sebelum memulai pekerjaan pencetakan.",
          ne: "मोल्डिङ कार्य सुरु गर्नु अघि तयारी अवस्था दर्ता गर्नुहोस्।",
        },
        steps: [
          {
            number: 1,
            title: {
              ja: "「INJ[事前準備]{じぜんじゅんび}」を おす",
              en: 'Press "INJ Pre-prep"',
              vi: 'Nhấn "Chuẩn bị INJ"',
              pt: 'Pressione "Pré-prep INJ"',
              tl: 'Pindutin ang "INJ Pre-prep"',
              id: 'Tekan "Pra-persiapan INJ"',
              ne: '"INJ पूर्व-तयारी" थिच्नुहोस्',
            },
            description: {
              ja: "メインメニューの[緑]{みどり}のボードのアイコンを タップします。",
              en: "Tap the green board icon on the main menu.",
              vi: "Chạm vào biểu tượng bảng màu xanh lá cây trên menu chính.",
              pt: "Toque no ícone do quadro verde no menu principal.",
              tl: "I-tap ang icon ng green board sa main menu.",
              id: "Ketuk ikon papan hijau di menu utama.",
              ne: "मुख्य मेनुमा रहेको हरियो बोर्ड आइकन ट्याप गर्नुहोस्।",
            },
            image: "/photo/2/スクリーンショット2.111 2026-04-13 090842.png",
          },
          {
            number: 2,
            title: {
              ja: "「[検索]{けんさく}」を おす",
              en: 'Press "Search"',
              vi: 'Nhấn "Tìm kiếm"',
              pt: 'Pressione "Pesquisar"',
              tl: 'Pindutin ang "Search"',
              id: 'Tekan "Cari"',
              ne: '"खोज" थिच्नुहोस्',
            },
            description: {
              ja: "[画面]{がめん}の「[検索]{けんさく}」ボタンを タップして、[一覧]{いちらん}を [出]{だ}します。",
              en: 'Tap the "Search" button on the screen to display the list.',
              vi: 'Chạm vào nút "Tìm kiếm" trên màn hình để hiển thị danh sách.',
              pt: 'Toque no botão "Pesquisar" na tela para exibir a lista.',
              tl: 'I-tap ang button na "Search" sa screen para ipakita ang listahan.',
              id: 'Ketuk tombol "Cari" di layar untuk menampilkan daftar.',
              ne: 'सूची प्रदर्शन गर्न स्क्रिनमा रहेको "खोज" बटन ट्याप गर्नुहोस्।',
            },
            image: "/photo/2/スクリーンショット2.112 2026-04-13 091009.png",
          },
          {
            number: 3,
            title: {
              ja: "データ（[行]{ぎょう}）を [選]{えら}び、「INJ[事前準備]{じぜんじゅんび}」を おす",
              en: 'Select Data and Press "INJ Pre-prep"',
              vi: 'Chọn dữ liệu và nhấn "Chuẩn bị INJ"',
              pt: 'Selecionar dados e pressionar "Pré-prep INJ"',
              tl: 'Pumili ng Data at Pindutin ang "INJ Pre-prep"',
              id: 'Pilih Data dan Tekan "Pra-persiapan INJ"',
              ne: 'डाटा छान्नुहोस् र "INJ पूर्व-तयारी" थिच्नुहोस्',
            },
            description: {
              ja: "[登録]{とうろく}したい [製品]{せいひん}の [行]{ぎょう}を タップして、[画面左下]{がめんひだりした}にある ボタンを タップします。",
              en: "Tap the row of the product you want to register, then tap the button at the bottom left of the screen.",
              vi: "Chạm vào hàng của sản phẩm bạn muốn đăng ký, sau đó chạm vào nút ở phía dưới bên trái màn hình.",
              pt: "Toque na linha do produto que você deseja registrar e, em seguida, toque no botão no canto inferior esquerdo da tela.",
              tl: "I-tap ang row ng produktong gusto mong i-register, pagkatapos ay i-tap ang button sa ibabang kaliwa ng screen.",
              id: "Ketuk baris produk yang ingin Anda daftarkan, lalu ketuk tombol di kiri bawah layar.",
              ne: "तपाईंले दर्ता गर्न चाहनुभएको उत्पादनको पङ्क्ति ट्याप गर्नुहोस्, त्यसपछि स्क्रिनको तल बायाँपट्टि रहेको बटन ट्याप गर्नुहोस्।",
            },
            image: "/photo/2/スクリーンショット2.113 2026-04-13 093527.png",
          },
          {
            number: 4,
            title: {
              ja: "「[確認数]{かくにんすう}」を いれる",
              en: 'Enter "Confirmed Count"',
              vi: 'Nhập "Số lượng xác nhận"',
              pt: 'Inserir "Contagem Confirmada"',
              tl: 'Ilagay ang "Confirmed Count"',
              id: 'Masukkan "Jumlah Terkonfirmasi"',
              ne: '"पुष्टि गरिएको गणना" प्रविष्ट गर्नुहोस्',
            },
            description: {
              ja: "[入力欄]{にゅうりょくらん}を タップして、[数量]{すうりょう}を いれます。",
              en: "Tap the input field and enter the quantity.",
              vi: "Chạm vào ô nhập liệu và nhập số lượng.",
              pt: "Toque no campo de entrada e insira a quantidade.",
              tl: "I-tap ang input field at ilagay ang dami.",
              id: "Ketuk kolom input dan masukkan jumlahnya.",
              ne: "इनपुट फिल्ड ट्याप गर्नुहोस् र मात्रा प्रविष्ट गर्नुहोस्।",
            },
            image: "/photo/2/スクリーンショット2.114 2026-04-13 094416-1.png",
          },
          {
            number: 5,
            title: {
              ja: "「[決定]{けってい}」を おす",
              en: 'Press "Confirm"',
              vi: 'Nhấn "Xác nhận"',
              pt: 'Pressione "Confirmar"',
              tl: 'Pindutin ang "Confirm"',
              id: 'Tekan "Konfirmasi"',
              ne: '"पुष्टि गर्नुहोस्" थिच्नुहोस्',
            },
            description: {
              ja: "[最後]{さいご}に [青]{あお}いボタンを おして [保存]{ほぞん}します。",
              en: "Finally, press the blue button to save.",
              vi: "Cuối cùng, nhấn nút màu xanh để lưu.",
              pt: "Finalmente, pressione o botão azul para salvar.",
              tl: "Sa huli, pindutin ang asul na button para i-save.",
              id: "Terakhir, tekan tombol biru untuk menyimpan.",
              ne: "अन्तमा, बचत गर्न नीलो बटन थिच्नुहोस्।",
            },
            image: "/photo/2/スクリーンショット2.115 2026-04-13 094453.png",
          },
        ],
      },
      {
        id: "material-input",
        pdfPage: 18,
        title: {
          ja: "[材料払出投入記録]{ざいりょうはらいだしとうにゅうきろく}を [登録]{とうろく}する",
          en: "Register Material Discharge/Input Record",
          vi: "Đăng ký ghi chép xả/nhập nguyên liệu",
          pt: "Registrar Registro de Descarga/Entrada de Material",
          tl: "I-register ang Material Discharge/Input Record",
          id: "Daftarkan Catatan Pengeluaran/Pemasukan Bahan",
          ne: "सामग्री डिस्चार्ज/इनपुट रेकर्ड दर्ता गर्नुहोस्",
        },
        content: {
          ja: "[使用]{しよう}する[材料]{ざいりょう}について [登録]{とうろく}します。",
          en: "Register the materials to be used.",
          vi: "Đăng ký các nguyên liệu sẽ được sử dụng.",
          pt: "Registre os materiais a serem usados.",
          tl: "I-register ang mga materyales na gagamitin.",
          id: "Daftarkan bahan yang akan digunakan.",
          ne: "प्रयोग गरिने सामग्रीहरू दर्ता गर्नुहोस्।",
        },
        steps: [
          {
            number: 1,
            title: {
              ja: "「[検索]{けんさく}」を おす",
              en: 'Press "Search"',
              vi: 'Nhấn "Tìm kiếm"',
              pt: 'Pressione "Pesquisar"',
              tl: 'Pindutin ang "Search"',
              id: 'Tekan "Cari"',
              ne: '"खोज" थिच्नुहोस्',
            },
            description: {
              ja: "「[検索]{けんさく}」をタップして INJ [事前準備一覧]{じぜんじゅんびいちらん}を [表示]{ひょうじ}させます。",
              en: 'Tap "Search" to display the INJ Pre-preparation list.',
              vi: 'Chạm vào "Tìm kiếm" để hiển thị danh sách chuẩn bị INJ.',
              pt: 'Toque em "Pesquisar" para exibir a lista de pré-preparação INJ.',
              tl: 'I-tap ang "Search" para ipakita ang listahan ng INJ Pre-preparation.',
              id: 'Ketuk "Cari" untuk menampilkan daftar pra-persiapan INJ.',
              ne: 'INJ पूर्व-तयारी सूची प्रदर्शन गर्न "खोज" ट्याप गर्नुहोस्।',
            },
            image: "/photo/2/スクリーンショット2.121 2026-04-13 095446.png",
          },
          {
            number: 2,
            title: {
              ja: "データ（[行]{ぎょう}）を [選]{えら}ぶ",
              en: "Select Data (Row)",
              vi: "Chọn dữ liệu (Hàng)",
              pt: "Selecionar dados (Linha)",
              tl: "Pumili ng Data (Row)",
              id: "Pilih Data (Baris)",
              ne: "डाटा (पङ्क्ति) छान्नुहोस्",
            },
            description: {
              ja: "[登録]{とうろく}したい [指示]{しじ}データを [選択]{せんたく}します。",
              en: "Select the instruction data to register.",
              vi: "Chọn dữ liệu hướng dẫn để đăng ký.",
              pt: "Selecione os dados de instrução para registrar.",
              tl: "Pumili ng data ng tagubilin na ire-register.",
              id: "Pilih data instruksi untuk didaftarkan.",
              ne: "दर्ता गर्न निर्देशन डाटा चयन गर्नुहोस्।",
            },
            image: "/photo/2/スクリーンショット2.122 2026-04-13 095519.png",
          },
          {
            number: 3,
            title: {
              ja: "[内容]{ないよう}を[確認]{かくにん}し、[投入]{とうにゅう}・[払出]{はらいだし}を[登録]{とうろく}する",
              en: "Check Details and Register Input/Discharge",
              vi: "Kiểm tra chi tiết và đăng ký Nhập/Xả",
              pt: "Verificar detalhes e registrar entrada/descarga",
              tl: "Suriin ang mga Detalye at Irehistro ang Input/Discharge",
              id: "Periksa Detail dan Daftarkan Pemasukan/Pengeluaran",
              ne: "विवरणहरू जाँच गर्नुहोस् र इनपुट/डिस्चार्ज दर्ता गर्नुहोस्",
            },
            description: {
              ja: "[内容]{ないよう}を[確認]{かくにん}して、[投入]{とうにゅう}または[払出]{はらいだし}をタップして[登録]{とうろく}します。",
              en: 'Verify the details and tap "Input" or "Discharge" to register.',
              vi: 'Xác minh chi tiết và chạm vào "Nhập" hoặc "Xả" để đăng ký.',
              pt: 'Verifique os detalhes e toque em "Entrada" ou "Descarga" para registrar.',
              tl: 'I-verify ang mga detalye at i-tap ang "Input" o "Discharge" para mag-register.',
              id: 'Verifikasi detail dan ketuk "Pemasukan" atau "Pengeluaran" untuk mendaftar.',
              ne: 'विवरणहरू प्रमाणित गर्नुहोस् र दर्ता गर्न "इनपुट" वा "डिस्चार्ज" ट्याप गर्नुहोस्।',
            },
            image: "/photo/2/スクリーンショット2.124 2026-04-13 132521.png",
            video: "https://drive.google.com/file/d/10AeVhhsG3sA_UwQjmMZF1rrEWb65o8kw/preview",
          },
          {
            number: 4,
            title: {
              ja: "「[払出]{はらいだし}」または「[投入]{とうにゅう}」を おす",
              en: 'Press "Discharge" or "Input"',
              vi: 'Nhấn "Xả" hoặc "Nhập"',
              pt: 'Pressione "Descarga" ou "Entrada"',
              tl: 'Pindutin ang "Discharge" o "Input"',
              id: 'Tekan "Pengeluaran" atau "Pemasukan"',
              ne: '"डिस्चार्ज" वा "इनपुट" थिच्नुहोस्',
            },
            description: {
              ja: "「[払出]{はらいだし}」または「[投入]{とうにゅう}」ボタンを タップして [登録]{とうろく}します。",
              en: 'Tap the "Discharge" or "Input" button to register.',
              vi: 'Chạm vào nút "Xả" hoặc "Nhập" để đăng ký.',
              pt: 'Toque no botão "Descarga" ou "Entrada" para registrar.',
              tl: 'I-tap ang button na "Discharge" o "Input" para mag-register.',
              id: 'Ketuk tombol "Pengeluaran" atau "Pemasukan" untuk mendaftar.',
              ne: '"डिस्चार्ज" वा "इनपुट" बटन ट्याप गरेर दर्ता गर्नुहोस्।',
            },
            image: "/photo/2/スクリーンショット2.124 2026-04-13 132521.png",
          },
        ],
      },
    ],
  },
  {
    id: SectionType.MOLDING,
    title: {
      ja: "3. つくる（[成形]{せいけい}）",
      en: "3. Production (Molding)",
      vi: "3. Sản xuất (Đúc)",
      pt: "3. Produção (Moldagem)",
      tl: "3. Produksyon (Molding)",
      id: "3. Produksi (Pencetakan)",
      ne: "3. उत्पादन (मोल्डिङ)",
    },
    icon: "🛠️",
    pages: [
      {
        id: "molding-start",
        pdfPage: 29,
        title: {
          ja: "[作業]{さぎょう}を はじめる",
          en: "Start Work",
          vi: "Bắt đầu công việc",
          pt: "Iniciar o trabalho",
          tl: "Simulan ang Trabaho",
          id: "Mulai Bekerja",
          ne: "काम सुरु गर्नुहोस्",
        },
        content: {
          ja: "[今日]{きょう}つくるものを [選]{えら}んで、スタートします。",
          en: "Select what to make today and start.",
          vi: "Chọn những gì cần làm hôm nay và bắt đầu.",
          pt: "Selecione o que fazer hoje e comece.",
          tl: "Piliin ang gagawin ngayong araw at magsimula.",
          id: "Pilih apa yang akan dibuat hari ini और mulai.",
          ne: "आज के बनाउने छनौट गर्नुहोस् र सुरु गर्नुहोस्।",
        },
        steps: [
          {
            number: 1,
            title: {
              ja: "つくるものを [選]{えら}ぶ",
              en: "Select Product",
              vi: "Chọn sản phẩm",
              pt: "Selecionar produto",
              tl: "Pumili ng Produkto",
              id: "Pilih Produk",
              ne: "उत्पादन छान्नुहोस्",
            },
            description: {
              ja: "「[検索]{けんさく}」をおして リストから [今日]{きょう}つくる[製品]{せいひん}を [選]{えら}んでタップします।",
              en: 'Press "Search" and tap the product you will make today from the list.',
              vi: 'Nhấn "Tìm kiếm" và chạm vào sản phẩm bạn sẽ làm hôm nay từ danh sách.',
              pt: 'Pressione "Pesquisar" e toque no produto que você fará hoje na lista.',
              tl: 'Pindutin ang "Search" at i-tap ang produktong gagawin mo ngayong araw mula sa lista.',
              id: 'Ketuk tombol "Cari" dan ketuk produk yang akan Anda buat hari ini dari daftar.',
              ne: 'सूचीबाट तपाईंले आज बनाउनुहुने उत्पादन "खोज" थिच्नुहोस् र ट्याप गर्नुहोस्।',
            },
            image: "/photo/3/スクリーンショット3-1 2026-03-29 161906.png",
          },
          {
            number: 2,
            title: {
              ja: "「[実績入力]{じっせきにゅうりょく}」を おす",
              en: 'Press "Result Input"',
              vi: 'Nhấn "Nhập kết quả"',
              pt: 'Pressione "Entrada de Resultado"',
              tl: 'Pindutin ang "Result Input"',
              id: 'Tekan "Input Hasil"',
              ne: '"नतिजा इनपुट" थिच्नुहोस्',
            },
            description: {
              ja: "[画面]{がめん}の[下]{した}にある [青]{あお}い「[実績入力]{じっせきにゅうりょく}」を タップします。",
              en: 'Tap the blue "Result Input" button at the bottom of the screen.',
              vi: 'Chạm vào nút "Nhập kết quả" màu xanh ở cuối màn hình.',
              pt: 'Toque no botão azul "Entrada de Resultado" na parte inferior da tela.',
              tl: 'I-tap ang asul na button na "Result Input" sa ibaba ng screen.',
              id: 'Ketuk tombol biru "Input Hasil" di bagian bawah layar.',
              ne: 'स्क्रिनको तल रहेको नीलो "नतिजा इनपुट" ボタン ट्याप गर्नुहोस्।',
            },
            image: "/photo/3/スクリーンショット3-2 2026-03-29 162605.png",
          },
          {
            number: 3,
            title: {
              ja: "シフトを [選]{えら}ぶ",
              en: "Select Shift",
              vi: "Chọn ca làm việc",
              pt: "Selecionar turno",
              tl: "Pumili ng Shift",
              id: "Pilih Shift",
              ne: "シフト छान्नुहोस्",
            },
            description: {
              ja: "[今]{いま}の[時間帯]{じかんたい}（A[勤]{きん}・B[勤]{きん}など）を [選]{えら}んで「[決定]{けってい}」を おすと、[記録]{きろく}が はじまるように なります।",
              en: 'Select the current time slot (Shift A, Shift B, etc.) and press "Confirm" to start recording.',
              vi: 'Chọn khung giờ hiện tại (Ca A, Ca B, v.व.) และ nhấn "Xác nhận" เพื่อเริ่มบันทึก।',
              pt: 'Selecione o intervalo de tempo atual (Turno A, Turno B, etc.) e pressione "Confirmar" para iniciar o registro.',
              tl: 'Pumili ng kasलुकश्यक time slot (Shift A, Shift B, atbp.) at pindutin ang "Confirm" para simulan ang pag-record.',
              id: 'Pilih slot waktu saat ini (Shift A, Shift B, dll.) और tekan "Konfirmasi" para mulai mencatat.',
              ne: 'हालको समय स्लट (शिफ्ट A, शिफ्ट B, आदि) छान्नुहोस् र रेकर्डिङ सुरु गर्न "पुष्टि गर्नुहोस्" थिच्नुहोस्।',
            },
            video:
              "https://drive.google.com/file/d/1UpjaQ39XxOv1Uj-Q9dxYrEPkONBgk70m/preview",
          },
        ],
      },
      {
        id: "box-number-registration",
        pdfPage: 34,
        title: {
          ja: "[箱]{はこ}[番号]{ばんごう}を [登録]{とうろく}する",
          en: "Register Box Number",
          vi: "Đăng ký số hộp",
          pt: "Registrar número da caixa",
          tl: "Irehistro ang Numero ng Kahon",
          id: "Daftarkan Nomor Kotak",
          ne: "बक्स नम्बर दर्ता गर्नुहोस्",
        },
        content: {
          ja: "[新]{あたら}しい[箱]{はこ}を つかうときに、[箱]{はこ}の[番号]{ばんごう}を [読]{よ}み[込]{こ}みます।",
          en: "Scan the box number when using a new box.",
          vi: "Quét số hộp khi sử dụng hộp mới.",
          pt: "Digitalize o número da caixa ao usar uma nova caixa.",
          tl: "I-scan ang numero ng kahon kapag gumayamit ng bagong kahon.",
          id: "Pindai nomor kotak saat menggunakan kotak baru.",
          ne: "नयाँ बक्स प्रयोग गर्दा बक्स नम्बर स्क्यान गर्नुहोस्।",
        },
        steps: [
          {
            number: 1,
            title: {
              ja: "[正規容器]{せいきようき}を [追加]{ついか}する[場合]{ばあい}",
              en: "When adding a regular container",
              vi: "Khi thêm thùng chứa thông thường",
              pt: "Ao adicionar um recipiente regular",
              tl: "Kapag nagdaragdag ng regular na lalagyan",
              id: "Saat menambahkan wadah reguler",
              ne: "नियमित कन्टेनर थप्दा",
            },
            description: {
              ja: "[正規容器]{せいきようき}の [完了時]{かんりょうじ}に [画面]{がめん}[中央]{ちゅうおう}の ボタンを [押]{お}します।",
              en: "Press the button in the center of the screen when the regular container is complete.",
              vi: "Nhấn nút ở giữa màn hình khi thùng chứa thông thường hoàn tất.",
              pt: "Pressione o botão no centro da tela quando o recipiente regular estiver concluído.",
              tl: "Pindutin ang button sa gitna ng screen kapag tapos na ang regular na lalagyan.",
              id: "Tekan tombol di tengah layar saat wadah reguler selesai.",
              ne: "नियमित कन्टेनर पूरा भएपछि स्क्रिनको बीचमा रहेको बटन थिच्नुहोस्।",
            },
            image: "/photo/3/スクリーンショット3.21 2026-03-29 173311.png",
          },
          {
            number: 2,
            title: {
              ja: "[正規容器]{せいきようき}と [仮容器]{かりようき}を [切]{き}り[替]{か}える[場合]{ばあい}",
              en: "When switching between regular and temporary containers",
              vi: "Khi chuyển đổi giữa thùng chứa thông thường and tạm thời",
              pt: "Ao alternar entre recipientes regulares e temporários",
              tl: "Kapag lumilipat sa pagitan ng regular at pansamantalang mga lalagyan",
              id: "Saat beralih antara wadah reguler dan sementara",
              ne: "नियमित र अस्थायी कन्टेनरहरू बीच स्विच गर्दा",
            },
            description: {
              ja: "[正規容器]{せいきようき}か [仮容器]{かりようき}か、[使]{つか}う [箱]{はこ}に [合]{あ}わせて [画面]{がめん}の [左下]{ひだりした}にある ボタンを [切]{き}り[替]{か}えます।",
              en: "Switch the button at the bottom left of the screen according to the type of box you are using (Regular or Temporary).",
              vi: "Chuyển đổi nút ở phía dưới bên trái màn hình tùy theo loại thùng bạn đang sử dụng (Thông thường hoặc Tạm thời).",
              pt: "Alterne o botão no canto inferior esquerdo da tela de acordo com o tipo de caixa que está usando (Regular ou Temporária).",
              tl: "I-switch ang button sa ibabang kaliwa ng screen ayon sa uri ng kahon na iyong ginagamit (Regular o Pansamantalang).",
              id: "Ganti tombol di kiri bawah layar sesuai dengan jenis kotak yang Anda gunakan (Reguler atau Sementara).",
              ne: "तपाईंले प्रयोग गरिरहनुभएको बक्सको प्रकार (नियमित वा अस्थायी) अनुसार स्क्रिनको तल बायाँपट्टिको बटन स्विच गर्नुहोस्।",
            },
            image: "/photo/3/スクリーンショット3.22 2026-03-29 173445.png",
          },
        ],
      },
    ],
  },
  {
    id: SectionType.CHECK,
    title: {
      ja: "4. [不良]{ふりょう}（だめなもの）",
      en: "4. Defects (NG)",
      vi: "4. Hàng lỗi (NG)",
      pt: "4. Defeitos (NG)",
      tl: "4. Mga Depekto (NG)",
      id: "4. Produk Cacat (NG)",
      ne: "4. दोषहरू (NG)",
    },
    icon: "⚠️",
    pages: [
      {
        id: "defect-input",
        pdfPage: 35,
        title: {
          ja: "[不良]{ふりょう}（だめなもの）を いれる",
          en: "Input Defects",
          vi: "Nhập hàng lỗi",
          pt: "Inserir Defeitos",
          tl: "I-input ang mga Depekto",
          id: "Input Produk Cacat",
          ne: "दोषहरू इनपुट गर्नुहोस्",
        },
        content: {
          ja: "[不良]{ふりょう}（だめなもの）が [出]{で}たときに おこないます।",
          en: "Used when defective products are produced.",
          vi: "Sử dụng khi có sản phẩm lỗi được sản xuất.",
          pt: "Usado quando produtos defeituosos são produzidos.",
          tl: "Ginagamit kapag may mga depektibong produkto na ginawa.",
          id: "Digunakan saat produk cacat diproduksi.",
          ne: "दोषपूर्ण उत्पादनहरू उत्पादन गर्दा प्रयोग गरिन्छ।",
        },
        steps: [
          {
            number: 1,
            title: {
              ja: "「[不良]{ふりょう}」を おす",
              en: 'Press "Defect"',
              vi: 'Nhấn "Hàng lỗi"',
              pt: 'Pressione "Defeito"',
              tl: 'Pindutin ang "Defect"',
              id: 'Tekan "Produk Cacat"',
              ne: '"दोष" थिच्नुहोस्',
            },
            description: {
              ja: "[画面]{がめん}の [下]{した}にある「[不良]{ふりょう}」タブを タップします।",
              en: 'Tap the "Defect" tab at the bottom of the screen.',
              vi: 'Chạm vào tab "Hàng lỗi" ở cuối màn hình.',
              pt: 'Toque na aba "Defeito" na parte inferior da tela.',
              tl: 'I-tap ang tab na "Defect" sa ibaba ng screen.',
              id: 'Ketuk tab "Produk Cacat" di bagian bawah layar.',
              ne: 'स्क्रिनको तल रहेको "दोष" ट्याब ट्याप गर्नुहोस्।',
            },
            image: "/photo/4/スクリーンショット4.11 2026-03-29 181559.png",
          },
          {
            number: 2,
            title: {
              ja: "[理由]{りゆう}を [選]{えら}ぶ",
              en: "Select Reason",
              vi: "Chọn lý do",
              pt: "Selecionar motivo",
              tl: "Pumili ng Dahilan",
              id: "Pilih Alasan",
              ne: "कारण छान्नुहोस्",
            },
            description: {
              ja: "「キズ」「シルバー」「[異物]{いぶつ}」など、だめだった[理由]{りゆう}を タップします।",
              en: 'Tap the reason for the defect, such as "Scratch", "Silver", or "Foreign Object".',
              vi: 'Chạm vào lý do lỗi, chẳng hạn như "Vết trầy", "Bạc", hoặc "Vật lạ".',
              pt: 'Toque no motivo do defeito, como "Arranhão", "Prata" ou "Objeto Estranho".',
              tl: 'I-tap ang dahilan ng depekto, gaya ng "Scratch", "Silver", o "Foreign Object".',
              id: 'Ketuk alasan cacat, seperti "Goresan", "Perak", atau "Benda Asing".',
              ne: 'दोषको कारण ट्याप गर्नुहोस्, जस्तै "कोर्नु", "चाँदी", वा "विदेशी वस्तु"।',
            },
            image: "/photo/4/スクリーンショット4.12 2026-03-29 181928.png",
          },
          {
            number: 3,
            title: {
              ja: "[数]{かず}を いれて「[登録]{とうろく}」する",
              en: 'Enter Number and "Register"',
              vi: 'Nhấn "Hàng lỗi"',
              pt: 'Pressione "Defeito"',
              tl: 'Pindutin ang "Defect"',
              id: 'Tekan "Produk Cacat"',
              ne: '"दोष" थिच्नुहोस्',
            },
            description: {
              ja: "[数]{かず}を いれて「ENTER」を おし、[最後]{さいご}に「[登録]{とうろく}」を タップします।",
              en: 'Enter the number, press "ENTER", and finally tap "Register".',
              vi: 'Nhập số, nhấn "ENTER", và cuối cùng chạm vào "Đăng ký".',
              pt: 'Insira o número, pressione "ENTER" e, finalmente, toque em "Registrar".',
              tl: 'Ilagay ang numero, pindutin ang "ENTER", at sa huli ay i-tap ang "Register".',
              id: 'Masukkan nomor, tekan "ENTER", dan terakhir ketuk "Daftar".',
              ne: 'नम्बर प्रविष्ट गर्नुहोस्, "ENTER" थिच्नुहोस्, र अन्तमा "दर्ता गर्नुहोस्" ट्याप गर्नुहोस्।',
            },
            image: "/photo/4/スクリーンショット4.13 2026-03-29 182921.png",
          },
        ],
      },
    ],
  },
  {
    id: SectionType.ADMIN,
    title: {
      ja: "5. [交代]{こうたい}・おわり",
      en: "5. Handover & End",
      vi: "5. Bàn giao & Kết thúc",
      pt: "5. Entrega e Fim",
      tl: "5. Handover at Tapos",
      id: "5. Serah Terima & Selesai",
      ne: "5. हस्तान्तरण र अन्त्य",
    },
    icon: "🏁",
    pages: [
      {
        id: "work-pause",
        pdfPage: 38,
        title: {
          ja: "[作業]{さぎょう}の[一時停止]{いちじていし}",
          en: "Temporary Work Stop",
          vi: "Tạm dừng công việc",
          pt: "Pausa temporária no trabalho",
          tl: "Pansamantalang Paghinto ng Trabaho",
          id: "Penghentian Kerja Sementara",
          ne: "कामको अस्थायी रोक",
        },
        content: {
          ja: "[休憩]{きゅうけい}や[機械]{きかい}トラブルなど[作業]{さぎょう}の[一時停止]{いちじていし}を[登録]{とうろく}します。",
          en: "Register temporary work stops such as breaks or machine trouble.",
          vi: "Đăng ký tạm dừng công việc như nghỉ giải lao hoặc sự cố máy móc.",
          pt: "Registre paradas temporárias de trabalho, como intervalos ou problemas na máquina.",
          tl: "Magrehistro ng mga pansamantalang paghinto ng trabaho gaya ng mga break o problema sa makina.",
          id: "Daftarkan penghentian kerja sementara seperti istirahat atau masalah mesin.",
          ne: "ब्रेक वा मेसिनको समस्या जस्ता कामको अस्थायी रोकहरू दर्ता गर्नुहोस्।",
        },
        steps: [
          {
            number: 1,
            title: {
              ja: "「[停止]{ていし}」を おす",
              en: 'Press "Stop"',
              vi: 'Nhấn "Dừng"',
              pt: 'Pressione "Parar"',
              tl: 'Pindutin ang "Stop"',
              id: 'Tekan "Berhenti"',
              ne: '"रोक्नुहोस्" थिच्नुहोस्',
            },
            description: {
              ja: "[画面]{がめん}[左]{ひだり}の［[停止]{ていし}］をタップします。",
              en: "Tap [Stop] on the left of the screen.",
              vi: "Chạm vào [Dừng] ở bên trái màn hình.",
              pt: "Toque em [Parar] à esquerda da tela.",
              tl: "I-tap ang [Stop] sa kaliwa ng screen.",
              id: "Ketuk [Berhenti] di sebelah kiri layar.",
              ne: "स्क्रिनको बायाँमा रहेको [रोक्नुहोस्] ट्याप गर्नुहोस्।",
            },
            image: "/photo/5/スクリーンショット5.11 2026-04-12 162930.png",
          },
          {
            number: 2,
            title: {
              ja: "[停止理由]{ていしりゆう}を [選]{えら}ぶ",
              en: "Select Stop Reason",
              vi: "Chọn lý do dừng",
              pt: "Selecionar motivo da parada",
              tl: "Pumili ng Dahilan ng Paghinto",
              id: "Pilih Alasan Berhenti",
              ne: "रोकिनुको कारण छान्नुहोस्",
            },
            description: {
              ja: "[停止理由]{ていしりゆう}[登録画面]{とうろくがめん}が[表示]{ひょうじ}されます。[停止理由]{ていしりゆう}を[選択]{せんたく}します。[一時停止]{いちじていし}の[開始時刻]{かいしじこく}、[終了時刻]{しゅうりょうじこく}（デフォルト[現在時刻]{げんざいじこく}）の[変更]{へんこう}も[可能]{かのう}です。",
              en: "The stop reason registration screen appears. Select the stop reason. The start and end times (default current time) for the temporary stop can also be changed.",
              vi: "Màn hình đăng ký lý do dừng xuất hiện. Chọn lý do dừng. Bạn cũng có thể thay đổi thời gian bắt đầu and kết thúc (mặc định là thời gian hiện tại) for việc tạm dừng.",
              pt: "A tela de registro do motivo da parada aparece. Selecione o motivo da parada. Os horários de início e término (horário atual padrão) para a parada temporária também podem ser alterados.",
              tl: "Lalabas ang screen ng pagpaparehistro ng dahilan ng paghinto. Piliin ang dahilan ng paghinto. Maaari ding baguhin ang simula at huling oras (default na kasalukuyang oras) para sa pansamantalang paghinto.",
              id: "Layar pendaftaran alasan berhenti muncul. Pilih alasan berhenti. Waktu mulai dan berakhir (waktu saat ini default) untuk penghentian sementara juga dapat diubah.",
              ne: "रोकिने कारण दर्ता स्क्रिन देखा पर्दछ। रोकिने कारण छान्नुहोस्। अस्थायी रोकको लागि सुरु र अन्त्य समय (पूर्वनिर्धारित हालको समय) पनि परिवर्तन गर्न सकिन्छ।",
            },
            image: "/photo/5/スクリーンショット5.12 2026-04-12 164503.png",
          },
          {
            number: 3,
            title: {
              ja: "「[登録]{とうろく}」する",
              en: "Register",
              vi: "Đăng ký",
              pt: "Registrar",
              tl: "Magrehistro",
              id: "Daftar",
              ne: "दर्ता गर्नुहोस्",
            },
            description: {
              ja: "［[登録]{とうろく}］をタップして[保存]{ほぞん}します。[作業履歴一覧]{さぎょうりれきいちらん}も[表示]{ひょうじ}されます。",
              en: "Tap [Register] to save. The work history list is also displayed.",
              vi: "Chạm vào [Đăng ký] để lưu. Danh sách lịch sử công việc cũng được hiển thị.",
              pt: "Toque em [Registrar] para salvar. A lista de histórico de trabalho também é exibida.",
              tl: "I-tap ang [Magrehistro] para i-save. Ipinapakita rin ang listahan ng kasaysayan ng trabaho.",
              id: "Ketuk [Daftar] untuk menyimpan. Daftar riwayat kerja juga ditampilkan.",
              ne: "बचत गर्न [दर्ता गर्नुहोस्] ट्याप गर्नुहोस्। कार्य इतिहास सूची भी प्रदर्शित हुन्छ।",
            },
            image: "/photo/5/スクリーンショット5.13 2026-04-12 164638.png",
          },
        ],
        notes: [
          {
            ja: "[停止理由]{ていしりゆう}を[登録]{とうろく}すると、[実績入力画面]{じっせきにゅうりょくがめん}に[戻]{もど}ります。[誤]{あやま}って[停止選択]{ていしせんたく}をした[場合]{ばあい}は、[停止理由]{ていしりゆう}「[取]{と}り[消]{け}し」で[登録]{とうろく}して[下]{くだ}さい。",
            en: 'After registering the stop reason, you return to the result input screen. If you selected stop by mistake, register with the reason "Cancel".',
            vi: 'Sau khi đăng ký lý do dừng, bạn sẽ quay lại màn hình nhập kết quả. Nếu bạn chọn dừng do nhầm lẫn, hãy đăng ký với lý do "Hủy bỏ".',
            pt: 'Após registrar o motivo da parada, você retorna à tela de entrada de resultados. Se você selecionou parar por engano, registre com o motivo "Cancelar".',
            tl: 'Pagkatapos irehistro ang dahilan ng paghinto, babalik ka sa screen ng result input. Kung nagkamali ka sa pagpili ng paghinto, magrehistro gamit ang dahilan na "Kanselahin".',
            id: 'Setelah mendaftarkan alasan berhenti, Anda kembali ke layar input hasil. Jika Anda salah memilih berhenti, daftarkan with alasan "Batal".',
            ne: 'रोकिने कारण दर्ता गरेपछि, तपाईं नतिजा इनपुट स्क्रिनमा फर्कनुहुन्छ। यदि तपाईंले गल्तीले रोक्ने विकल्प छान्नुभयो भने, "रद्द गर्नुहोस्" कारणका साथ दर्ता गर्नुहोस्।',
          },
        ],
      },
      {
        id: "operator-change",
        pdfPage: 40,
        title: {
          ja: "[担当者]{たんとうしゃ}を かえる（[交代]{こうたい}）",
          en: "Change Operator (Handover)",
          vi: "Thay đổi người vận hành (Bàn giao)",
          pt: "Alterar Operador (Entrega)",
          tl: "Palitan ang Operator (Handover)",
          id: "Ganti Operator (Serah Terima)",
          ne: "अपरेटर परिवर्तन गर्नुहोस् (हस्तान्तरण)",
        },
        content: {
          ja: "[同]{おな}じシフト[内]{ない}での[交代]{こうたい}や[休憩]{きゅうけい}の[時]{とき}に[使]{つか}います。",
          en: "Used for handovers or breaks within the same shift.",
          vi: "Sử dụng khi bàn giao hoặc nghỉ giải lao trong cùng một ca.",
          pt: "Usado para entregas ou intervalos dentro do mesmo turno.",
          tl: "Ginagamit para sa mga handover o break sa loob ng parehong shift.",
          id: "Digunakan untuk serah terima atau istirahat dalam shift yang sama.",
          ne: "एउटै शिफ्ट भित्र हस्तान्तरण वा ब्रेकको लागि प्रयोग गरिन्छ।",
        },
        steps: [
          {
            number: 1,
            title: {
              ja: "「[交代]{こうたい}」を おす",
              en: 'Press "Handover"',
              vi: 'Nhấn "Bàn giao"',
              pt: 'Pressione "Entrega"',
              tl: 'Pindutin ang "Handover"',
              id: 'Tekan "Serah Terima"',
              ne: '"हस्तान्तरण" थिच्नुहोस्',
            },
            description: {
              ja: "[実績入力画面]{じっせきにゅうりょくがめん}の [右上]{みぎうえ}にある「[交代]{こうたい}」を おします。",
              en: 'Press "Handover" at the top right of the result input screen.',
              vi: 'Nhấn "Bàn giao" ở phía trên bên phải của màn hình nhập kết quả.',
              pt: 'Pressione "Entrega" no canto superior direito da tela de entrada de resultados.',
              tl: 'Pindutin ang "Handover" sa kanang itaas ng screen ng result input.',
              id: 'Tekan "Serah Terima" di kanan atas layar input hasil.',
              ne: 'नतिजा इनपुट स्क्रिनको माथिल्लो दायाँमा "हस्तान्तरण" थिच्नुहोस्।',
            },
            image: "/photo/5/スクリーンショット5.21 2026-03-29 214308.png",
          },
          {
            number: 2,
            title: {
              ja: "[次]{つぎ}の[人]{ひと}を [選]{えら}ぶ",
              en: "Select Next Person",
              vi: "Chọn người tiếp theo",
              pt: "Selecionar próxima pessoa",
              tl: "Piliin ang Susunod na Tao",
              id: "Pilih Orang Berikutnya",
              ne: "अर्को व्यक्ति छान्नुहोस्",
            },
            description: {
              ja: "リストから、[次]{つぎ}に[作業]{さぎょう}する[人]{ひと}の [名前]{なまえ}を [選]{えら}んでください。",
              en: "Please select the name of the next person to work from the list.",
              vi: "Vui lòng chọn tên của người tiếp theo làm việc từ danh sách.",
              pt: "Selecione o nome da próxima pessoa a trabalhar na lista.",
              tl: "Pakipili ang pangalan ng susunod na taong magtatrabaho mula sa listahan.",
              id: "Silakan pilih nama orang berikutnya yang akan bekerja dari daftar.",
              ne: "कृपया सूचीबाट काम गर्न अर्को व्यक्तिको नाम छान्नुहोस्।",
            },
            image: "/photo/5/スクリーンショット5.22 2026-03-29 214438.png",
          },
          {
            number: 3,
            title: {
              ja: "「[決定]{けってい}」を おす",
              en: 'Press "Confirm"',
              vi: 'Nhấn "Xác nhận"',
              pt: 'Pressione "Confirmar"',
              tl: 'Pindutin ang "Confirm"',
              id: 'Tekan "Konfirmasi"',
              ne: '"पुष्टि गर्नुहोस्" थिच्नुहोस्',
            },
            description: {
              ja: "[右上]{みぎうえ}の [青]{あお}いボタンを おして [完了]{かんりょう}です。",
              en: "Press the blue button at the top right to complete.",
              vi: "Nhấn nút màu xanh ở phía trên bên phải để hoàn tất.",
              pt: "Pressione o botão azul no canto superior direito para concluir.",
              tl: "Pindutin ang asul na button sa kanang itaas para makumpleto.",
              id: "Tekan tombol biru di kanan atas untuk menyelesaikan.",
              ne: "पूरा गर्न माथिल्लो दायाँमा रहेको नीलो बटन थिच्नुहोस्।",
            },
            image: "/photo/5/スクリーンショット5.23 2026-03-29 214612.png",
          },
        ],
      },
      {
        id: "shift-change",
        pdfPage: 39,
        title: {
          ja: "シフト[変更]{へんこう}",
          en: "Shift Change",
          vi: "Thay đổi ca làm việc",
          pt: "Mudança de Turno",
          tl: "Pagbabago ng Shift",
          id: "Perubahan Shift",
          ne: "शिफ्ट परिवर्तन",
        },
        content: {
          ja: "定時でシフトが変わるときに行います。[作業者]{さぎょうしゃ}のシフト[区分変更]{くぶんへんこう}と、[締]{し}め[入力]{にゅうりょく}を[行]{おこな}います。",
          en: "Performed when shifts change at scheduled times. Change the operator's shift category and perform closing input.",
          vi: "Thực hiện khi ca làm việc thay đổi theo thời gian quy định. Thay đổi phân loại ca của người vận hành and thực hiện nhập kết thúc.",
          pt: "Realizado quando os turnos mudam nos horários agendados. Altere a categoria de turno do operador e realize a entrada de fechamento.",
          tl: "Isinasagawa kapag nagbago ang mga shift sa mga nakatakdang oras. Baguhin ang kategorya ng shift ng operator at isagawa ang closing input.",
          id: "Dilakukan saat shift berubah pada waktu yang dijadwalkan. Ubah kategori shift operator dan lakukan input penutupan.",
          ne: "निर्धारित समयमा शिफ्टहरू परिवर्तन हुँदा प्रदर्शन गरिन्छ। अपरेटरको शिफ्ट श्रेणी परिवर्तन गर्नुहोस् र बन्द इनपुट प्रदर्शन गर्नुहोस्।",
        },
        steps: [
          {
            number: 1,
            title: {
              ja: "「シフト[変更]{へんこう}」を おす",
              en: 'Press "Shift Change"',
              vi: 'Nhấn "Thay đổi ca"',
              pt: 'Pressione "Mudar Turno"',
              tl: 'Pindutin ang "Shift Change"',
              id: 'Tekan "Perubahan Shift"',
              ne: '"शिफ्ट परिवर्तन" थिच्नुहोस्',
            },
            description: {
              ja: "［シフト[変更]{へんこう}］をタップします。",
              en: "Tap [Shift Change].",
              vi: "Chạm vào [Thay đổi ca].",
              pt: "Toque em [Mudar Turno].",
              tl: "I-tap ang [Shift Change].",
              id: "Ketuk [Perubahan Shift].",
              ne: "[シフト परिवर्तन] ट्याप गर्नुहोस्।",
            },
            image: "/photo/5/スクリーンショット5.31 2026-04-12 164910.png",
          },
          {
            number: 2,
            title: {
              ja: "ハ[数登録]{すうとうろく}を する",
              en: "Register Fractions",
              vi: "Đăng ký số lẻ",
              pt: "Registrar frações",
              tl: "Magrehistro ng mga Fraction",
              id: "Daftarkan Pecahan",
              ne: "अंशहरू दर्ता गर्नुहोस्",
            },
            description: {
              ja: "ハ[数登録画面]{すうとうろくがめん}が[表示]{ひょうじ}されます。[現在]{げんざい}シフトでの[実績数]{じっせきすう}を[入力]{にゅうりょく}し［[登録]{とうろく}］をタップします。",
              en: "The fraction registration screen appears. Enter the results for the current shift and tap [Register].",
              vi: "Màn hình đăng ký số lẻ xuất hiện. Nhập kết quả cho ca hiện tại and chạm vào [Đăng ký].",
              pt: "A tela de registro de frações aparece. Insira os resultados do turno atual e toque em [Registrar].",
              tl: "Lalabas ang screen ng pagpaparehistro ng fraction. Ilagay ang mga resulta para sa kasalukuyang shift at i-tap ang [Magrehistro].",
              id: "Layar pendaftaran pecahan muncul. Masukkan hasil untuk shift saat ini dan ketuk [Daftar].",
              ne: "अंश दर्ता स्क्रिन देखा पर्दछ। हालको शिफ्टको लागि नतिजाहरू प्रविष्ट गर्नुहोस् र [दर्ता गर्नुहोस्] ट्याप गर्नुहोस्।",
            },
            image: "/photo/5/スクリーンショット5.32 2026-04-12 191920.png",
          },
          {
            number: 3,
            title: {
              ja: "[実績登録]{じっせきとうろく}を する",
              en: "Register Results",
              vi: "Đăng ký kết quả",
              pt: "Registrar resultados",
              tl: "Magrehistro ng mga Resulta",
              id: "Daftarkan Hasil",
              ne: "नतिजाहरू दर्ता गर्नुहोस्",
            },
            description: {
              ja: "[生産実績入力画面]{せいせいじっせきにゅうりょくがめん}が[表示]{ひょうじ}されます。［[実績登録]{じっせきとうろく}］をタップして[登録]{とうろく}します。",
              en: "The production result input screen appears. Tap [Register Results] to register.",
              vi: "Màn hình nhập kết quả sản xuất xuất hiện. Chạm vào [Đăng ký kết quả] để đăng ký.",
              pt: "A tela de entrada de resultados de produção aparece. Toque em [Registrar Resultados] para registrar.",
              tl: "Lalabas ang screen ng pag-input ng resulta ng produksyon. I-tap ang [Magrehistro ng mga Resulta] para magrehistro.",
              id: "Layar input hasil produksi muncul. Ketuk [Daftarkan Hasil] para mendaftar.",
              ne: "उत्पादन नतिजा इनपुट स्क्रिन देखा पर्दछ। दर्ता गर्न [नतिजाहरू दर्ता गर्नुहोस्] ट्याप गर्नुहोस्।",
            },
            image: "/photo/5/スクリーンショット5.33 2026-04-12 193217.png",
          },
          {
            number: 4,
            title: {
              ja: "[次]{つぎ}の シフトを [選]{えら}ぶ",
              en: "Select Next Shift",
              vi: "Chọn ca tiếp theo",
              pt: "Selecionar próximo turno",
              tl: "Pumili ng Susunod na Shift",
              id: "Pilih Shift Berikutnya",
              ne: "अर्को शिफ्ट छान्नुहोस्",
            },
            description: {
              ja: "シフト[入力画面]{にゅうりょくがめん}が[表示]{ひょうじ}されます。[担当者]{たんとうしゃ}とシフト[開始日時]{かいしにちじ}を[入力]{にゅうりょく}し[右下]{みぎした}の[決定]{けってい}をタップします。[登録後]{とうろくご}、[生産実績入力画面]{せいせいじっせきにゅうりょくがめん}に[戻]{もど}ります。",
              en: "The shift input screen appears. Enter the operator and shift start date/time, then tap Confirm at the bottom right. After registration, you return to the production result input screen.",
              vi: "Màn hình nhập ca xuất hiện. Nhập người vận hành and ngày/giờ bắt đầu ca, sau đó chạm vào Xác nhận ở phía dưới bên phải. Sau khi đăng ký, bạn sẽ quay lại màn hình nhập kết quả sản xuất.",
              pt: "A tela de entrada de turno aparece. Insira o operador e a data/hora de início do turno e toque em Confirmar no canto inferior direito. Após o registro, você retorna à tela de entrada de resultados de produção.",
              tl: "Lalabas ang screen ng pag-input ng shift. Ilagay ang operator at petsa/oras ng simula ng shift, pagkatapos ay i-tap ang Confirm sa kanang ibaba. Pagkatapos ng pagpaparehistro, babalik ka sa screen ng pag-input ng resulta ng produksyon.",
              id: "Layar input shift muncul. Masukkan operator dan tanggal/waktu mulai shift, lalu ketuk Konfirmasi di kanan bawah. Setelah pendaftaran, Anda kembali ke layar input hasil produksi.",
              ne: "शिफ्ट इनपुट स्क्रिन देखा पर्दछ। अपरेटर र शिफ्ट सुरु हुने मिति/समय प्रविष्ट गर्नुहोस्, त्यसपछि तल दायाँमा पुष्टि गर्नुहोस् ट्याप गर्नुहोस्। दर्ता पछि, तपाईं उत्पादन नतिजा इनपुट स्क्रिनमा फर्कनुहुन्छ।",
            },
            image: "/photo/5/スクリーンショット5.34 2026-04-12 192708.png",
          },
        ],
      },
      {
        id: "work-end",
        pdfPage: 45,
        title: {
          ja: "[作業]{さぎょう}を おわらせる",
          en: "End Work",
          vi: "Kết thúc công việc",
          pt: "Encerrar o trabalho",
          tl: "Tapusin ang Trabaho",
          id: "Selesaikan Pekerjaan",
          ne: "काम समाप्त गर्नुहोस्",
        },
        content: {
          ja: "その[日]{ひ}の [仕事]{しごと}が [全部]{ぜんぶ}おわったときです。",
          en: "When all the work for the day is finished.",
          vi: "Khi tất cả công việc trong ngày đã hoàn thành.",
          pt: "Quando todo o trabalho do dia estiver concluído.",
          tl: "Kapag tapos na ang lahat ng trabaho para sa araw na iyon.",
          id: "Saat semua pekerjaan hari itu selesai.",
          ne: "जब दिनको सबै काम समाप्त हुन्छ।",
        },
        steps: [
          {
            number: 1,
            title: {
              ja: "「[作業終了]{さぎょうしゅうりょう}」を おす",
              en: 'Press "End Work"',
              vi: 'Nhấn "Kết thúc công việc"',
              pt: 'Pressione "Encerrar Trabalho"',
              tl: 'Pindutin ang "End Work"',
              id: 'Tekan "Selesai Bekerja"',
              ne: '"काम समाप्त गर्नुहोस्" थिच्नुहोस्',
            },
            description: {
              ja: "[画面]{がめん}の[左]{ひだり}にある [赤]{あか}い「[作業終了]{さぎょうしゅうりょう}」ボタンを タップします。",
              en: 'Tap the red "End Work" button on the left side of the screen.',
              vi: 'Chạm vào nút "Kết thúc công việc" màu đỏ ở phía bên trái màn hình.',
              pt: 'Toque no botão vermelho "Encerrar Trabalho" no lado esquerdo da tela.',
              tl: 'I-tap ang pulang button na "End Work" sa kaliwang bahagi ng screen.',
              id: 'Ketuk tombol "Selesai Bekerja" berwarna merah di sisi kiri layar.',
              ne: 'स्क्रिनको बायाँ छेउमा रहेको रातो "काम समाप्त गर्नुहोस्" बटन ट्याप गर्नुहोस्।',
            },
            image: "/photo/5/スクリーンショット5.41 2026-04-12 171407.png",
          },
          {
            number: 2,
            title: {
              ja: "[最後]{さいご}の[数]{かず}を [確認]{かくにん}する",
              en: "Confirm Final Count",
              vi: "Xác nhận số lượng cuối cùng",
              pt: "Confirmar contagem final",
              tl: "Kumpirmahin ang Huling Bilang",
              id: "Konfirmasi Jumlah Akhir",
              ne: "अन्तिम गणना पुष्टि गर्नुहोस्",
            },
            description: {
              ja: "つくった[数]{かず}と [箱]{はこ}の[数]{かず}が [合]{あ}っているか [確認]{かくにん}して「[次]{つぎ}へ」を おします。",
              en: 'Check if the produced count and box count match, then press "Next".',
              vi: 'Kiểm tra xem số lượng sản xuất và số lượng thùng có khớp không, sau đó nhấn "Tiếp theo".',
              pt: 'Verifique se a contagem produzida e a contagem de caixas coincidem e pressione "Próximo".',
              tl: 'Suriin kung tugma ang bilang ng ginawa at bilang ng kahon, pagkatapos ay pindutin ang "Next".',
              id: 'Periksa apakah jumlah yang diproduksi dan jumlah kotak sesuai, lalu tekan "Berikutnya".',
              ne: 'उत्पादन गरिएको गणना र बक्स गणना मिल्छ कि छैन जाँच गर्नुहोस्, त्यसपछि "अर्को" थिच्नुहोस्।',
            },
            image: "/photo/5/スクリーンショット5.42 2026-04-12 175736.png",
          },
          {
            number: 3,
            title: {
              ja: "「[実績登録]{じっせきとうろく}」を おす",
              en: 'Press "Register Result"',
              vi: 'Nhấn "Đăng ký kết quả"',
              pt: 'Pressione "Registrar Resultado"',
              tl: 'Pindutin ang "Register Result"',
              id: 'Tekan "Daftar Hasil"',
              ne: '"नतिजा दर्ता गर्नुहोस्" थिच्नुहोस्',
            },
            description: {
              ja: "[廃棄]{はいき}の[量]{りょう}を[入力]{にゅうりょく}する[画面]{がめん}が[表示]{ひょうじ}されます。[廃棄]{はいき}があれば[数量]{すうりょう}を[入力]{にゅうりょく}し［[廃棄]{はいき}］をタップします。[廃棄量]{はいきりょう}の[入力]{にゅうりょく}が[終]{お}わったら[画面下中央]{がめんしたちゅうおう}の[赤]{あか}いアイコンをタップします。[最後]{さいご}に[最終確認]{さいしゅうかくにん}の[画面]{がめん}で[数量]{すうりょう}を[確認]{かくにん}して[登録完了]{とうろくかんりょう}です。",
              en: "The waste amount input screen will be displayed. If there is waste, enter the quantity and tap [Waste]. When you have finished entering the waste amount, tap the red icon in the bottom center of the screen. Finally, check the quantity on the final confirmation screen to complete registration.",
              vi: "Màn hình nhập lượng phế phẩm sẽ hiển thị. Nếu có phế phẩm, hãy nhập số lượng và nhấn [Phế phẩm]. Sau khi nhập xong lượng phế phẩm, hãy nhấn vào biểu tượng màu đỏ ở giữa phía dưới màn hình. Cuối cùng, kiểm tra số lượng trên màn hình xác nhận cuối cùng để hoàn tất đăng ký.",
              pt: "A tela de entrada da quantidade de resíduos será exibida. Se houver resíduos, insira a quantidade e toque em [Resíduos]. Quando terminar de inserir a quantidade de resíduos, toque no ícone vermelho no centro inferior da tela. Por fim, verifique a quantidade na tela de confirmação final para concluir o registro.",
              tl: "Lalabas ang screen para sa pag-input ng dami ng waste. Kung may waste, ilagay ang dami at i-tap ang [Waste]. Pagkatapos ilagay ang dami ng waste, i-tap ang pulang icon sa ibabang gitna ng screen. Sa huli, suriin ang dami sa final confirmation screen para makumpleto ang pagpaparehistro.",
              id: "Layar input jumlah limbah akan ditampilkan. Jika ada limbah, masukkan jumlahnya và ketuk [Limbah]. Setelah selesai memasukkan jumlah limbah, ketuk ikon merah di tengah bawah layar. Terakhir, periksa jumlahnya pada layar konfirmasi akhir untuk menyelesaikan pendaftaran.",
              ne: "फोहोर मात्रा इनपुट स्क्रिन प्रदर्शित हुनेछ। यदि फोहोर छ भने, मात्रा प्रविष्ट गर्नुहोस् र [फोहोर] ट्याप गर्नुहोस्। जब तपाईंले फोहोर मात्रा प्रविष्ट गरिसक्नुहुन्छ, स्क्रिनको तल केन्द्रमा रहेको रातो आइकन ट्याप गर्नुहोस्। अन्तमा, दर्ता पूरा गर्न अन्तिम पुष्टिकरण स्क्रिनमा मात्रा जाँच गर्नुहोस्।",
            },
            video:
              "https://drive.google.com/file/d/1vhEIlSYCVvGmetQGngYrN6nw4AkVs4Uc/preview",
          },
        ],
        notes: [
          {
            ja: "[予定]{よてい}の[数]{かず}と ちがうときは、[確認]{かくにん}メッセージが [出]{で}ます。OKなら「OK」を おしてください。",
            en: 'If the count is different from the planned number, a confirmation message will appear. If it is OK, please press "OK".',
            vi: 'Nếu số lượng khác with số lượng dự kiến, một thông báo xác nhận sẽ xuất hiện. Nếu ổn, vui lòng nhấn "OK".',
            pt: 'Se a contagem for diferente do número planejado, uma mensagem de confirmação aparecerá. Se estiver OK, pressione "OK".',
            tl: 'Kung ang bilang ay iba sa nakaplanong numero, may lalabas na confirmation message. Kung OK ito, pakipindot ang "OK".',
            id: 'Jika jumlahnya berbeda dari angka yang direncanakan, pesan konfirmasi akan muncul. Jika sudah OK, silakan tekan "OK".',
            ne: 'यदि गणना योजना गरिएको संख्या भन्दा फरक छ भने, एक पुष्टिकरण सन्देश देखा पर्नेछ। यदि यो ठीक छ भने, कृपया "OK" थिच्नुहोस्।',
          },
        ],
      },
    ],
  },
];
